export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const POST_ALL_CATEGORIES = 'POST_ALL_CATEGORIES'
export const UPDATE_ALL_CATEGORIES = 'UPDATE_ALL_CATEGORIES'
export const DELETE_ALL_CATEGORIES = 'DELETE_ALL_CATEGORIES'