export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const POST_ALL_PRODUCTS = 'POST_ALL_PRODUCTS'
export const UPDATE_ALL_PRODUCTS = 'UPDATE_ALL_PRODUCTS'
export const DELETE_ALL_PRODUCTS = 'DELETE_ALL_PRODUCTS'
